apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mythrion/kubernetes-environment.git
    targetRevision: HEAD
    path: rabbit

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
